import {lang,t,localize} from './i18n.js';
import {normalize,simulate,demoTariffs,numericFields} from './domain.js';
import {sampleInvoice,stages,ingest,DemoExtractor} from './extraction.js';
/** @param {string} id @returns {HTMLElement} */
function el(id){const node=document.getElementById(id);if(!node)throw new Error('Missing UI element');return node;}
/** @param {string} id @returns {HTMLInputElement} */
function inputEl(id){return /** @type {HTMLInputElement} */ (el(id));}
const decimal = new Intl.NumberFormat(lang==='es'?'es-ES':'en-IE',{maximumFractionDigits:3});
const percentage = new Intl.NumberFormat(lang==='es'?'es-ES':'en-IE',{minimumFractionDigits:1,maximumFractionDigits:1});
const money = new Intl.NumberFormat(lang==='es'?'es-ES':'en-IE',{style:'currency',currency:'EUR'});
/** @param {number} n */ const euro=n=>money.format(n);
/** @param {string} text */ function escape(text){return text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));}
const screens=['idle','processing','review','simulating','results'];
let controller=new AbortController();
let state='idle';
/** @type {import('./domain.js').Invoice} */ let invoice={...sampleInvoice};
/** @param {string} next */
function show(next){state=next;for(const s of screens)el(s).hidden=s!==next;el('error').hidden=true;document.querySelectorAll('.stepper li').forEach((li,i)=>{li.removeAttribute('aria-current');if(i===(next==='results'||next==='simulating'?2:next==='review'?1:0))li.setAttribute('aria-current','step');});el('status').textContent=t(next==='processing'?'Processing a synthetic fixture.':next==='results'?'Scenario results ready.':next==='review'?'Structured sample ready for review.':'');if(next!=='processing'){el('workspace').scrollIntoView({block:'start'});const heading=el(next).querySelector('h1');if(heading instanceof HTMLElement){heading.tabIndex=-1;heading.focus({preventScroll:true});}}}
function reset(){controller.abort();controller=new AbortController();invoice={...sampleInvoice};inputEl('file').value='';inputEl('confirmed').checked=false;for(const id of ['fields','json','bars','breakdown','result-summary','prices','assumptions'])el(id).replaceChildren();show('idle');}
/** @param {unknown} error */ function fail(error){el('error-message').textContent=t(error instanceof Error?error.message:'Unable to process this document. Try the sample.');el('error').hidden=false;el('error').scrollIntoView({block:'nearest'});}
function invoiceMarkup(){return `<article class="invoice" aria-label="Fictional sample electricity invoice"><div class="invoice-head"><h2>Northlight<br><small>Demo Energy</small></h2><span>ELECTRICITY BILL<br>DEMO-INV-0001<br>Fictional customer</span></div><p class="fiction">CREATED FROM SCRATCH / SYNTHETIC DATA</p><dl><dt>Supply reference (not a real CUPS)</dt><dd>DEMO-SUPPLY-0001</dd><dt>Access tariff</dt><dd>2.0TD</dd><dt>Billing period</dt><dd>01 Apr – 01 May 2026</dd><dt>Billing days · end exclusive</dt><dd>30</dd></dl><hr><dl><dt>Contracted power P1 / P2</dt><dd>4.6 / 4.6 kW</dd><dt>Consumption P1</dt><dd>85 kWh</dd><dt>Consumption P2</dt><dd>70 kWh</dd><dt>Consumption P3</dt><dd>125 kWh</dd><dt>Total consumption</dt><dd>280 kWh</dd></dl><hr><dl><dt>Energy · 280 × €0.22</dt><dd>€61.60</dd><dt>Power · 4.6 × 30 × (€0.09 + €0.04)</dt><dd>€17.94</dd><dt>Illustrative levy · 4%</dt><dd>€3.18</dd><dt>Meter rental</dt><dd>€0.90</dd><dt>Illustrative VAT · 20%</dt><dd>€16.72</dd></dl><div class="invoice-total"><span>Total amount</span><strong>€100.34</strong></div><p class="small">Fictional company, reference and figures. Not a commercial invoice.</p></article>`;}
el('sample-preview').innerHTML=invoiceMarkup();el('review-preview').innerHTML=invoiceMarkup();
const groups=[{name:'Supply',fields:[['supplier','Supplier','text'],['supply','Demo supply reference','text'],['tariff','Access tariff','text']]},{name:'Billing period',fields:[['from','From · inclusive','date'],['to','To · exclusive','date']]},{name:'Contracted power · kW',fields:[['power1','P1 power','text'],['power2','P2 power','text']]},{name:'Consumption · kWh',fields:[['consumption1','P1 consumption','text'],['consumption2','P2 consumption','text'],['consumption3','P3 consumption','text']]},{name:'Invoice amounts · €',fields:[['energy','Energy','text'],['power','Power','text'],['tax','Illustrative levy','text'],['rental','Meter rental','text'],['vat','Illustrative VAT','text'],['total','Invoice total','text']]}];
function renderReview(){el('fields').innerHTML=groups.map(g=>`<fieldset><legend>${g.name}</legend><div class="field-grid">${g.fields.map(([key,label,type])=>`<label for="${key}">${label}<input id="${key}" name="${key}" type="${type}" ${numericFields.includes(key)?'inputmode="decimal"':''} ${key==='tariff'?'readonly':''} value="${escape(String(/** @type {Record<string,unknown>} */ (invoice)[key]??''))}" maxlength="120"><span class="field-meta ${key==='consumption2'?'review':''}">${key==='consumption2'?'Review suggested · sample flag':'Extracted · synthetic fixture'}</span></label>`).join('')}</div></fieldset>`).join('');el('json').textContent=JSON.stringify(invoice,null,2);inputEl('confirmed').checked=false;localize(el('fields'));}
/** @param {File|null} file */
async function process(file){if(state==='processing'||state==='simulating')return;controller.abort();controller=new AbortController();const signal=controller.signal;show('processing');el('pipeline').innerHTML=stages.map((s,i)=>`<li id="stage-${i}"><span>${s}</span><span>Pending</span></li>`).join('');localize(el('pipeline'));try{if(!file){const response=await fetch('sample-invoice.pdf',{signal});if(!response.ok)throw new Error('Sample could not be loaded. Try again.');file=new File([await response.blob()],'sample-invoice.pdf',{type:'application/pdf'});}await ingest(file);file=null;signal.throwIfAborted();const result=await new DemoExtractor().extract(index=>{stages.forEach((_,i)=>{el('stage-'+i).className=i<index?'done':i===index?'active':'';(/** @type {HTMLElement} */ (el('stage-'+i).querySelector('span:last-child'))).textContent=t(i<index?'Checked':i===index?'Running':'Pending');});el('status').textContent=t(stages[index]);},signal);invoice=result.invoice;renderReview();show('review');}catch(error){if(signal.aborted)return;show('idle');fail(error);}finally{inputEl('file').value='';}}
el('sample').addEventListener('click',()=>process(null));
inputEl('file').addEventListener('change',()=>process(inputEl('file').files?.[0]||null));
const dropzone=el('dropzone');dropzone.addEventListener('dragover',e=>{e.preventDefault();dropzone.classList.add('dragging');});dropzone.addEventListener('dragleave',()=>dropzone.classList.remove('dragging'));dropzone.addEventListener('drop',e=>{e.preventDefault();dropzone.classList.remove('dragging');if(e.dataTransfer?.files.length!==1){fail(new Error('Drop one invoice at a time.'));return;}process(e.dataTransfer.files[0]);});
document.querySelectorAll('.reset').forEach(b=>b.addEventListener('click',reset));el('dismiss').addEventListener('click',()=>{el('error').hidden=true;});el('edit').addEventListener('click',()=>show('review'));
el('review-form').addEventListener('input',e=>{el('error').hidden=true;const input=e.target;if(input instanceof HTMLInputElement&&input.id!=='confirmed'){inputEl('confirmed').checked=false;const meta=input.nextElementSibling;if(meta){meta.textContent=t(input.value.trim()?'Edited · human input':'Missing · enter a value');meta.className='field-meta'+(input.value.trim()?'':' review');input.setAttribute('aria-invalid',String(!input.value.trim()));}}});
el('review-form').addEventListener('submit',async e=>{e.preventDefault();const form=/** @type {HTMLFormElement} */(el('review-form'));try{if(!inputEl('confirmed').checked)throw new Error('Confirm that you reviewed the extracted values.');const raw=Object.fromEntries(new FormData(form));const {validateExtraction}=await import('./domain.js');invoice=validateExtraction(raw);const normalized=normalize(invoice);el('json').textContent=JSON.stringify(invoice,null,2);show('simulating');const signal=controller.signal;await new Promise(resolve=>setTimeout(resolve,100));if(signal.aborted)return;renderResults(normalized);show('results');}catch(error){if(state==='simulating')show('review');fail(error);}});
/** @param {import('./domain.js').NormalizedInvoice} input */
function renderResults(input){const results=simulate(input);const current=results[0];const best=results.slice(1).reduce((a,b)=>a.annual<b.annual?a:b);el('assumptions').textContent=`${input.days} billing days · ${input.consumption.reduce((a,b)=>a+b,0)} kWh · same daily profile extrapolated to 365 days.`;el('result-summary').innerHTML=`<div><p>Current estimated cost / year</p><strong>${euro(current.annual)}</strong><p>${euro(current.monthly)} monthly average · reviewed invoice baseline</p></div><div><p>Lowest synthetic scenario / ${best.name}</p><strong>${euro(best.annual)}</strong><p>${euro(best.monthly)} monthly average · demo tariff</p></div>`;const max=Math.max(1,...results.map(r=>r.annual));el('bars').innerHTML=results.map((r,i)=>`<div class="${i===0?'baseline':''}"><div class="bar-head"><div><b>${r.name}</b> <small>${i===0?'Reviewed invoice':'Demo tariff'}</small></div><strong>${euro(r.annual)} / year</strong></div><div class="track" aria-hidden="true"><div class="fill" style="width:${r.annual/max*100}%"></div></div><div class="bar-foot"><span>${euro(r.monthly)} / month</span><span>${i===0?'Comparison baseline':`${r.difference>0?'+':''}${euro(r.difference)} vs current · ${r.percent===null?'percentage unavailable':`${r.percent>0?'+':''}${percentage.format(r.percent)}%`}`}</span></div></div>`).join('');el('breakdown').innerHTML=results.map(r=>`<tr><th scope="row">${r.name}</th><td>${euro(r.energy)}</td><td>${euro(r.power)}</td><td>${euro(r.taxes)}</td><td>${euro(r.other)}</td><td><strong>${euro(r.annual)}</strong></td></tr>`).join('');el('prices').innerHTML=demoTariffs.map(t=>`<tr><th scope="row">${t.name} · demo</th><td>${t.energy.map(n=>decimal.format(n)).join(' / ')}</td><td>${t.power.map(n=>decimal.format(n)).join(' / ')}</td><td>${decimal.format(t.daily)}</td></tr>`).join('');for(const id of ['assumptions','result-summary','bars','breakdown','prices'])localize(el(id));}

// Keep portfolio navigation in the selected language, including a direct demo visit.
document.documentElement.lang=lang;
document.title=lang==='es'?'Energy Simulator — Demo pública':'Energy Simulator — Public Demo';
document.querySelectorAll('a[href]').forEach(node=>{
  const href=node.getAttribute('href');
  if(href && (href.includes('../../') || href==='./')) {
    const url=new URL(href,location.href);url.searchParams.set('lang',lang);node.setAttribute('href',url.href);
  }
});
localize(document);
